# Site
title:       Kevin Albert
email:       kevinalbert@protonmail.ch
author:      Kevin Albert
description: "Yet another unnecessary programming blog"
baseurl:     ""
url:         "https://kevin-albert.github.io"
date_format: "%b %-d, %Y"
logo: halve.png
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/unsplash-image-10.jpg             # this image will be shown on post list page
  default-post: images/unsplash-gallery-image-3.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
#email:             email
#google.plus:        username
twitter:            "@kevybabysc"
#facebook:           username
github:             kevin-albert
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          kevin-albert
#xing:              username
instagram:          _keleven
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
soundcloud:        supple-congress
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
